[[projects]]
url = "https://github.com/sodasmile1121/mips-pipelined-cpu"
description = "A MIPS pipelined CPU project implemented in Verilog as part of a computer organization course."

[[projects]]
url = "https://github.com/sodasmile1121/text-based-dungeon"
description = "An independently developed text-based dungeon game using OOP purely in C++."

[[projects]]
url = "https://github.com/sodasmile1121/facebook-simulator"
description = "An independently developed Facebook simulator using HTML and CSS."

[[projects]]
url = "https://github.com/sodasmile1121/javascript-amazon-project"
description = "A mimic Amazon shopping website completed as part of an online JavaScript tutorial course."